### ISSUE TITLE
传输方式从ws转到mkcp时失败

### ISSUE THREAD

**Issue by Seekerzero** [Jrohy/v2ray.fun#6]
Traceback (most recent call last):
  File "/usr/local/v2ray.fun/config_modify/stream.py", line 48, in <module>
    v2ray_util.choice_stream(new_stream_network, index_dict)
  File "/usr/local/v2ray.fun/base_util/v2ray_util.py", line 23, in choice_stream
    write_json.write_stream_network("mkcp","none", index_dict)
  File "/usr/local/v2ray.fun/write_json.py", line 120, in write_stream_network
    with open('json_template/kcp.json', 'r') as stream_file:
FileNotFoundError: [Errno 2] No such file or directory: 'json_template/kcp.json'
Redirecting to /bin/systemctl restart v2ray.service

**Comment by Jrohy** [comment]
已修复, 请更新下脚本```source <(curl -sL https://git.io/vpHpE) keep```
